# Site settings
title: No B.S. recipes
email: ben@thelocust.org
description: Great recipes with no bullshit. 
baseurl: ""
twitter_username: mynameiswilson
github_username:  mynameiswilson

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
